package com.chenzt.shoppingbackend.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class AddressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public AddressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAddress1IsNull() {
            addCriterion("address1 is null");
            return (Criteria) this;
        }

        public Criteria andAddress1IsNotNull() {
            addCriterion("address1 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress1EqualTo(String value) {
            addCriterion("address1 =", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotEqualTo(String value) {
            addCriterion("address1 <>", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1GreaterThan(String value) {
            addCriterion("address1 >", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1GreaterThanOrEqualTo(String value) {
            addCriterion("address1 >=", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1LessThan(String value) {
            addCriterion("address1 <", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1LessThanOrEqualTo(String value) {
            addCriterion("address1 <=", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1Like(String value) {
            addCriterion("address1 like", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotLike(String value) {
            addCriterion("address1 not like", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1In(List<String> values) {
            addCriterion("address1 in", values, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotIn(List<String> values) {
            addCriterion("address1 not in", values, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1Between(String value1, String value2) {
            addCriterion("address1 between", value1, value2, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotBetween(String value1, String value2) {
            addCriterion("address1 not between", value1, value2, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress2IsNull() {
            addCriterion("address2 is null");
            return (Criteria) this;
        }

        public Criteria andAddress2IsNotNull() {
            addCriterion("address2 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress2EqualTo(String value) {
            addCriterion("address2 =", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotEqualTo(String value) {
            addCriterion("address2 <>", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2GreaterThan(String value) {
            addCriterion("address2 >", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2GreaterThanOrEqualTo(String value) {
            addCriterion("address2 >=", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2LessThan(String value) {
            addCriterion("address2 <", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2LessThanOrEqualTo(String value) {
            addCriterion("address2 <=", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2Like(String value) {
            addCriterion("address2 like", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotLike(String value) {
            addCriterion("address2 not like", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2In(List<String> values) {
            addCriterion("address2 in", values, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotIn(List<String> values) {
            addCriterion("address2 not in", values, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2Between(String value1, String value2) {
            addCriterion("address2 between", value1, value2, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotBetween(String value1, String value2) {
            addCriterion("address2 not between", value1, value2, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress3IsNull() {
            addCriterion("address3 is null");
            return (Criteria) this;
        }

        public Criteria andAddress3IsNotNull() {
            addCriterion("address3 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress3EqualTo(String value) {
            addCriterion("address3 =", value, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress3NotEqualTo(String value) {
            addCriterion("address3 <>", value, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress3GreaterThan(String value) {
            addCriterion("address3 >", value, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress3GreaterThanOrEqualTo(String value) {
            addCriterion("address3 >=", value, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress3LessThan(String value) {
            addCriterion("address3 <", value, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress3LessThanOrEqualTo(String value) {
            addCriterion("address3 <=", value, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress3Like(String value) {
            addCriterion("address3 like", value, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress3NotLike(String value) {
            addCriterion("address3 not like", value, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress3In(List<String> values) {
            addCriterion("address3 in", values, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress3NotIn(List<String> values) {
            addCriterion("address3 not in", values, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress3Between(String value1, String value2) {
            addCriterion("address3 between", value1, value2, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress3NotBetween(String value1, String value2) {
            addCriterion("address3 not between", value1, value2, "address3");
            return (Criteria) this;
        }

        public Criteria andAddress4IsNull() {
            addCriterion("address4 is null");
            return (Criteria) this;
        }

        public Criteria andAddress4IsNotNull() {
            addCriterion("address4 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress4EqualTo(String value) {
            addCriterion("address4 =", value, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress4NotEqualTo(String value) {
            addCriterion("address4 <>", value, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress4GreaterThan(String value) {
            addCriterion("address4 >", value, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress4GreaterThanOrEqualTo(String value) {
            addCriterion("address4 >=", value, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress4LessThan(String value) {
            addCriterion("address4 <", value, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress4LessThanOrEqualTo(String value) {
            addCriterion("address4 <=", value, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress4Like(String value) {
            addCriterion("address4 like", value, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress4NotLike(String value) {
            addCriterion("address4 not like", value, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress4In(List<String> values) {
            addCriterion("address4 in", values, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress4NotIn(List<String> values) {
            addCriterion("address4 not in", values, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress4Between(String value1, String value2) {
            addCriterion("address4 between", value1, value2, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress4NotBetween(String value1, String value2) {
            addCriterion("address4 not between", value1, value2, "address4");
            return (Criteria) this;
        }

        public Criteria andAddress5IsNull() {
            addCriterion("address5 is null");
            return (Criteria) this;
        }

        public Criteria andAddress5IsNotNull() {
            addCriterion("address5 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress5EqualTo(String value) {
            addCriterion("address5 =", value, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress5NotEqualTo(String value) {
            addCriterion("address5 <>", value, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress5GreaterThan(String value) {
            addCriterion("address5 >", value, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress5GreaterThanOrEqualTo(String value) {
            addCriterion("address5 >=", value, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress5LessThan(String value) {
            addCriterion("address5 <", value, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress5LessThanOrEqualTo(String value) {
            addCriterion("address5 <=", value, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress5Like(String value) {
            addCriterion("address5 like", value, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress5NotLike(String value) {
            addCriterion("address5 not like", value, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress5In(List<String> values) {
            addCriterion("address5 in", values, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress5NotIn(List<String> values) {
            addCriterion("address5 not in", values, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress5Between(String value1, String value2) {
            addCriterion("address5 between", value1, value2, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress5NotBetween(String value1, String value2) {
            addCriterion("address5 not between", value1, value2, "address5");
            return (Criteria) this;
        }

        public Criteria andAddress6IsNull() {
            addCriterion("address6 is null");
            return (Criteria) this;
        }

        public Criteria andAddress6IsNotNull() {
            addCriterion("address6 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress6EqualTo(String value) {
            addCriterion("address6 =", value, "address6");
            return (Criteria) this;
        }

        public Criteria andAddress6NotEqualTo(String value) {
            addCriterion("address6 <>", value, "address6");
            return (Criteria) this;
        }

        public Criteria andAddress6GreaterThan(String value) {
            addCriterion("address6 >", value, "address6");
            return (Criteria) this;
        }

        public Criteria andAddress6GreaterThanOrEqualTo(String value) {
            addCriterion("address6 >=", value, "address6");
            return (Criteria) this;
        }

        public Criteria andAddress6LessThan(String value) {
            addCriterion("address6 <", value, "address6");
            return (Criteria) this;
        }

        public Criteria andAddress6LessThanOrEqualTo(String value) {
            addCriterion("address6 <=", value, "address6");
            return (Criteria) this;
        }

        public Criteria andAddress6Like(String value) {
            addCriterion("address6 like", value, "address6");
            return (Criteria) this;
        }

        public Criteria andAddress6NotLike(String value) {
            addCriterion("address6 not like", value, "address6");
            return (Criteria) this;
        }

        public Criteria andAddress6In(List<String> values) {
            addCriterion("address6 in", values, "address6");
            return (Criteria) this;
        }

        public Criteria andAddress6NotIn(List<String> values) {
            addCriterion("address6 not in", values, "address6");
            return (Criteria) this;
        }

        public Criteria andAddress6Between(String value1, String value2) {
            addCriterion("address6 between", value1, value2, "address6");
            return (Criteria) this;
        }

        public Criteria andAddress6NotBetween(String value1, String value2) {
            addCriterion("address6 not between", value1, value2, "address6");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(LocalDateTime value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(LocalDateTime value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(LocalDateTime value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(LocalDateTime value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<LocalDateTime> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<LocalDateTime> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(LocalDateTime value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(LocalDateTime value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(LocalDateTime value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(LocalDateTime value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<LocalDateTime> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<LocalDateTime> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 19 11:25:46 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}