package com.chenzt.shoppingbackend.entity;

import java.time.LocalDateTime;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address1
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    private String address1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address2
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address3
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    private String address3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address4
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    private String address4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address5
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    private String address5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address6
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    private String address6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.user_id
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ctime
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    private LocalDateTime ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.mtime
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    private LocalDateTime mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address1
     *
     * @return the value of address.address1
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address1
     *
     * @param address1 the value for address.address1
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address2
     *
     * @return the value of address.address2
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address2
     *
     * @param address2 the value for address.address2
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address3
     *
     * @return the value of address.address3
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public String getAddress3() {
        return address3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address3
     *
     * @param address3 the value for address.address3
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address4
     *
     * @return the value of address.address4
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public String getAddress4() {
        return address4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address4
     *
     * @param address4 the value for address.address4
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setAddress4(String address4) {
        this.address4 = address4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address5
     *
     * @return the value of address.address5
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public String getAddress5() {
        return address5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address5
     *
     * @param address5 the value for address.address5
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setAddress5(String address5) {
        this.address5 = address5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address6
     *
     * @return the value of address.address6
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public String getAddress6() {
        return address6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address6
     *
     * @param address6 the value for address.address6
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setAddress6(String address6) {
        this.address6 = address6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.user_id
     *
     * @return the value of address.user_id
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.user_id
     *
     * @param userId the value for address.user_id
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ctime
     *
     * @return the value of address.ctime
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public LocalDateTime getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ctime
     *
     * @param ctime the value for address.ctime
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.mtime
     *
     * @return the value of address.mtime
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public LocalDateTime getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.mtime
     *
     * @param mtime the value for address.mtime
     *
     * @mbg.generated Fri Feb 19 11:25:46 CST 2021
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }
}