package com.chenzt.shoppingbackend.entity;

import java.time.LocalDateTime;

public class Approve {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approve.id
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approve.shop_id
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approve.user_id
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approve.ctime
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    private LocalDateTime ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approve.mtime
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    private LocalDateTime mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approve.id
     *
     * @return the value of approve.id
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approve.id
     *
     * @param id the value for approve.id
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approve.shop_id
     *
     * @return the value of approve.shop_id
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approve.shop_id
     *
     * @param shopId the value for approve.shop_id
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approve.user_id
     *
     * @return the value of approve.user_id
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approve.user_id
     *
     * @param userId the value for approve.user_id
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approve.ctime
     *
     * @return the value of approve.ctime
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    public LocalDateTime getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approve.ctime
     *
     * @param ctime the value for approve.ctime
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approve.mtime
     *
     * @return the value of approve.mtime
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    public LocalDateTime getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approve.mtime
     *
     * @param mtime the value for approve.mtime
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }
}