package com.chenzt.shoppingbackend.entity;

import java.time.LocalDateTime;

public class Img {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.id
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img1
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    private String img1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img2
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    private String img2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img3
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    private String img3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img4
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    private String img4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img5
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    private String img5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img6
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    private String img6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.goods_id
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.ctime
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    private LocalDateTime ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.mtime
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    private LocalDateTime mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.id
     *
     * @return the value of img.id
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.id
     *
     * @param id the value for img.id
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img1
     *
     * @return the value of img.img1
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public String getImg1() {
        return img1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img1
     *
     * @param img1 the value for img.img1
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public void setImg1(String img1) {
        this.img1 = img1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img2
     *
     * @return the value of img.img2
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public String getImg2() {
        return img2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img2
     *
     * @param img2 the value for img.img2
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public void setImg2(String img2) {
        this.img2 = img2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img3
     *
     * @return the value of img.img3
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public String getImg3() {
        return img3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img3
     *
     * @param img3 the value for img.img3
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public void setImg3(String img3) {
        this.img3 = img3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img4
     *
     * @return the value of img.img4
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public String getImg4() {
        return img4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img4
     *
     * @param img4 the value for img.img4
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public void setImg4(String img4) {
        this.img4 = img4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img5
     *
     * @return the value of img.img5
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public String getImg5() {
        return img5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img5
     *
     * @param img5 the value for img.img5
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public void setImg5(String img5) {
        this.img5 = img5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img6
     *
     * @return the value of img.img6
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public String getImg6() {
        return img6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img6
     *
     * @param img6 the value for img.img6
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public void setImg6(String img6) {
        this.img6 = img6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.goods_id
     *
     * @return the value of img.goods_id
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.goods_id
     *
     * @param goodsId the value for img.goods_id
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.ctime
     *
     * @return the value of img.ctime
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public LocalDateTime getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.ctime
     *
     * @param ctime the value for img.ctime
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.mtime
     *
     * @return the value of img.mtime
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public LocalDateTime getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.mtime
     *
     * @param mtime the value for img.mtime
     *
     * @mbg.generated Fri Feb 19 15:00:30 CST 2021
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }
}