package com.chenzt.shoppingbackend.entity;

import java.time.LocalDateTime;

public class Img {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.name
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.url
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.goods_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.ctime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private LocalDateTime ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.mtime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private LocalDateTime mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.id
     *
     * @return the value of img.id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.id
     *
     * @param id the value for img.id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.name
     *
     * @return the value of img.name
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.name
     *
     * @param name the value for img.name
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.url
     *
     * @return the value of img.url
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.url
     *
     * @param url the value for img.url
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.goods_id
     *
     * @return the value of img.goods_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.goods_id
     *
     * @param goodsId the value for img.goods_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.ctime
     *
     * @return the value of img.ctime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public LocalDateTime getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.ctime
     *
     * @param ctime the value for img.ctime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.mtime
     *
     * @return the value of img.mtime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public LocalDateTime getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.mtime
     *
     * @param mtime the value for img.mtime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }
}