package com.chenzt.shoppingbackend.entity;

import java.time.LocalDateTime;

public class NewArrivals {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_arrivals.goods_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_arrivals.ctime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private LocalDateTime ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_arrivals.mtime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private LocalDateTime mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_arrivals.goods_id
     *
     * @return the value of new_arrivals.goods_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_arrivals.goods_id
     *
     * @param goodsId the value for new_arrivals.goods_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_arrivals.ctime
     *
     * @return the value of new_arrivals.ctime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public LocalDateTime getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_arrivals.ctime
     *
     * @param ctime the value for new_arrivals.ctime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_arrivals.mtime
     *
     * @return the value of new_arrivals.mtime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public LocalDateTime getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_arrivals.mtime
     *
     * @param mtime the value for new_arrivals.mtime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }
}