package com.chenzt.shoppingbackend.entity;

import java.time.LocalDateTime;

public class Orderr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderr.id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderr.adress
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    private String adress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderr.username
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderr.goodsname
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderr.phone
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderr.user_id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderr.goods_id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderr.shop_id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderr.status
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderr.ctime
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    private LocalDateTime ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderr.mtime
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    private LocalDateTime mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderr.id
     *
     * @return the value of orderr.id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderr.id
     *
     * @param id the value for orderr.id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderr.adress
     *
     * @return the value of orderr.adress
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderr.adress
     *
     * @param adress the value for orderr.adress
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public void setAdress(String adress) {
        this.adress = adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderr.username
     *
     * @return the value of orderr.username
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderr.username
     *
     * @param username the value for orderr.username
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderr.goodsname
     *
     * @return the value of orderr.goodsname
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderr.goodsname
     *
     * @param goodsname the value for orderr.goodsname
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderr.phone
     *
     * @return the value of orderr.phone
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderr.phone
     *
     * @param phone the value for orderr.phone
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderr.user_id
     *
     * @return the value of orderr.user_id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderr.user_id
     *
     * @param userId the value for orderr.user_id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderr.goods_id
     *
     * @return the value of orderr.goods_id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderr.goods_id
     *
     * @param goodsId the value for orderr.goods_id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderr.shop_id
     *
     * @return the value of orderr.shop_id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderr.shop_id
     *
     * @param shopId the value for orderr.shop_id
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderr.status
     *
     * @return the value of orderr.status
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderr.status
     *
     * @param status the value for orderr.status
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderr.ctime
     *
     * @return the value of orderr.ctime
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public LocalDateTime getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderr.ctime
     *
     * @param ctime the value for orderr.ctime
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderr.mtime
     *
     * @return the value of orderr.mtime
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public LocalDateTime getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderr.mtime
     *
     * @param mtime the value for orderr.mtime
     *
     * @mbg.generated Sun Apr 11 15:20:42 CST 2021
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }
}