package com.chenzt.shoppingbackend.entity;

import java.time.LocalDateTime;

public class OrderHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.goodsname
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.username
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.address
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.phone
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.flavor
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String flavor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.price
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.count
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.url
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.user_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.goods_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.shop_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.ctime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private LocalDateTime ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.mtime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    private LocalDateTime mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.id
     *
     * @return the value of order_history.id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.id
     *
     * @param id the value for order_history.id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.goodsname
     *
     * @return the value of order_history.goodsname
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.goodsname
     *
     * @param goodsname the value for order_history.goodsname
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.username
     *
     * @return the value of order_history.username
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.username
     *
     * @param username the value for order_history.username
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.address
     *
     * @return the value of order_history.address
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.address
     *
     * @param address the value for order_history.address
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.phone
     *
     * @return the value of order_history.phone
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.phone
     *
     * @param phone the value for order_history.phone
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.flavor
     *
     * @return the value of order_history.flavor
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getFlavor() {
        return flavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.flavor
     *
     * @param flavor the value for order_history.flavor
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setFlavor(String flavor) {
        this.flavor = flavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.price
     *
     * @return the value of order_history.price
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.price
     *
     * @param price the value for order_history.price
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.count
     *
     * @return the value of order_history.count
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.count
     *
     * @param count the value for order_history.count
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.url
     *
     * @return the value of order_history.url
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.url
     *
     * @param url the value for order_history.url
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.user_id
     *
     * @return the value of order_history.user_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.user_id
     *
     * @param userId the value for order_history.user_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.goods_id
     *
     * @return the value of order_history.goods_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.goods_id
     *
     * @param goodsId the value for order_history.goods_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.shop_id
     *
     * @return the value of order_history.shop_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.shop_id
     *
     * @param shopId the value for order_history.shop_id
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.ctime
     *
     * @return the value of order_history.ctime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public LocalDateTime getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.ctime
     *
     * @param ctime the value for order_history.ctime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.mtime
     *
     * @return the value of order_history.mtime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public LocalDateTime getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.mtime
     *
     * @param mtime the value for order_history.mtime
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }
}