package com.chenzt.shoppingbackend.entity;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.name
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.status
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.address
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.user_id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.manager_id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.category_id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.describe
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.id
     *
     * @return the value of shop.id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.id
     *
     * @param id the value for shop.id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.name
     *
     * @return the value of shop.name
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.name
     *
     * @param name the value for shop.name
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.status
     *
     * @return the value of shop.status
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.status
     *
     * @param status the value for shop.status
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.address
     *
     * @return the value of shop.address
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.address
     *
     * @param address the value for shop.address
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.user_id
     *
     * @return the value of shop.user_id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.user_id
     *
     * @param userId the value for shop.user_id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.manager_id
     *
     * @return the value of shop.manager_id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.manager_id
     *
     * @param managerId the value for shop.manager_id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.category_id
     *
     * @return the value of shop.category_id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.category_id
     *
     * @param categoryId the value for shop.category_id
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.describe
     *
     * @return the value of shop.describe
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.describe
     *
     * @param describe the value for shop.describe
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    public void setDescribe(String describe) {
        this.describe = describe;
    }
}