package com.chenzt.shoppingbackend.mapper;

import com.chenzt.shoppingbackend.entity.ApproveHistory;
import com.chenzt.shoppingbackend.entity.ApproveHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApproveHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    long countByExample(ApproveHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int deleteByExample(ApproveHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int insert(ApproveHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int insertSelective(ApproveHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    List<ApproveHistory> selectByExample(ApproveHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    ApproveHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") ApproveHistory record, @Param("example") ApproveHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByExample(@Param("record") ApproveHistory record, @Param("example") ApproveHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByPrimaryKeySelective(ApproveHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByPrimaryKey(ApproveHistory record);
}