package com.chenzt.shoppingbackend.mapper;

import com.chenzt.shoppingbackend.entity.Approve;
import com.chenzt.shoppingbackend.entity.ApproveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApproveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    long countByExample(ApproveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int deleteByExample(ApproveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int insert(Approve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int insertSelective(Approve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    List<Approve> selectByExample(ApproveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    Approve selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") Approve record, @Param("example") ApproveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByExample(@Param("record") Approve record, @Param("example") ApproveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByPrimaryKeySelective(Approve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByPrimaryKey(Approve record);
}