package com.chenzt.shoppingbackend.mapper;

import com.chenzt.shoppingbackend.entity.NewArrivals;
import com.chenzt.shoppingbackend.entity.NewArrivalsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewArrivalsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_arrivals
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    long countByExample(NewArrivalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_arrivals
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int deleteByExample(NewArrivalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_arrivals
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int insert(NewArrivals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_arrivals
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int insertSelective(NewArrivals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_arrivals
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    List<NewArrivals> selectByExample(NewArrivalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_arrivals
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") NewArrivals record, @Param("example") NewArrivalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_arrivals
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByExample(@Param("record") NewArrivals record, @Param("example") NewArrivalsExample example);
}