package com.chenzt.shoppingbackend.mapper;

import com.chenzt.shoppingbackend.entity.Orderr;
import com.chenzt.shoppingbackend.entity.OrderrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderr
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    long countByExample(OrderrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderr
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int deleteByExample(OrderrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderr
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderr
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int insert(Orderr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderr
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int insertSelective(Orderr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderr
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    List<Orderr> selectByExample(OrderrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderr
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    Orderr selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderr
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") Orderr record, @Param("example") OrderrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderr
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByExample(@Param("record") Orderr record, @Param("example") OrderrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderr
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByPrimaryKeySelective(Orderr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderr
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByPrimaryKey(Orderr record);
}