package com.chenzt.shoppingbackend.mapper;

import com.chenzt.shoppingbackend.entity.OrderHistory;
import com.chenzt.shoppingbackend.entity.OrderHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    long countByExample(OrderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int deleteByExample(OrderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int insert(OrderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int insertSelective(OrderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    List<OrderHistory> selectByExample(OrderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    OrderHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrderHistory record, @Param("example") OrderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByExample(@Param("record") OrderHistory record, @Param("example") OrderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByPrimaryKeySelective(OrderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_history
     *
     * @mbg.generated Fri May 07 18:06:44 CST 2021
     */
    int updateByPrimaryKey(OrderHistory record);
}