package com.chenzt.shoppingbackend.mapper;

import com.chenzt.shoppingbackend.entity.ShopGoods;
import com.chenzt.shoppingbackend.entity.ShopGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    long countByExample(ShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    int deleteByExample(ShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    int insert(ShopGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    int insertSelective(ShopGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    List<ShopGoods> selectByExample(ShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    ShopGoods selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    int updateByExampleSelective(@Param("record") ShopGoods record, @Param("example") ShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    int updateByExample(@Param("record") ShopGoods record, @Param("example") ShopGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    int updateByPrimaryKeySelective(ShopGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods
     *
     * @mbg.generated Wed Jan 06 09:55:00 CST 2021
     */
    int updateByPrimaryKey(ShopGoods record);
}