package com.chenzt.shoppingbackend.mapper;

import com.chenzt.shoppingbackend.entity.ShopManageHistory;
import com.chenzt.shoppingbackend.entity.ShopManageHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopManageHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_manage_history
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    long countByExample(ShopManageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_manage_history
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    int deleteByExample(ShopManageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_manage_history
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_manage_history
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    int insert(ShopManageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_manage_history
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    int insertSelective(ShopManageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_manage_history
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    List<ShopManageHistory> selectByExample(ShopManageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_manage_history
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    ShopManageHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_manage_history
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    int updateByExampleSelective(@Param("record") ShopManageHistory record, @Param("example") ShopManageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_manage_history
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    int updateByExample(@Param("record") ShopManageHistory record, @Param("example") ShopManageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_manage_history
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    int updateByPrimaryKeySelective(ShopManageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_manage_history
     *
     * @mbg.generated Wed Apr 21 16:04:49 CST 2021
     */
    int updateByPrimaryKey(ShopManageHistory record);
}